export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO'
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR'

export const COMENZAR_OBTENER_PRODUCTOS = 'COMENZAR_OBTENER_PRODUCTOS'
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO'
export const OBTENER_PRODUCTOS_ERROR = 'OBTENER_PRODUCTOS_ERROR'

export const PRODUCTO_ELIMINAR = 'PRODUCTO_ELIMINAR'
export const PRODUCTO_ELIMINDO_EXITO = 'PRODUCTO_ELIMINDO_EXITO'
export const PRODUCTO_ELIMINDO_ERROR = 'PRODUCTO_ELIMINDO_ERROR'

// export const PRODUCTO_SELECCIONADO = 'PRODUCTO_SELECCIONADO';


export const PRODUCTO_EDITAR = 'PRODUCTO_EDITAR';
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'


